name: Build with VS 2017

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore BorderlessGaming.sln

    - name: Build solution
      shell: powershell
      run: |
        msbuild BorderlessGaming.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload build output
      uses: actions/upload-artifact@v3
      with:
        name: BuildOutput
        path: |
          BorderlessGaming\bin\Release\
          BorderlessGaming.Logic\bin\Release\
